### ISSUE TITLE
tune.py consumes too much memory after ctrl+c interruption

### ISSUE THREAD

**Issue by fsmosca** [thomasahle/fastchess#2]
### Environment
windows 7
python 3.7.3
scikit-optimize v0.5.2
scikit-learn-0.21.3
python-chess 0.28.2
numpy-1.16.2

### Description
Tried the tune.py and after 100 / 1000 games I sent ctrl+c, it tried to summarize best values but looking at the task manager it is consuming memory as high as 500 MB per sec. At around 3GB of memory usage (my pc has 12 GB), it crashed with the following later console messages. I could not get the earlier part of the console error messages because it is clipped.

```
Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python37\lib\asyncio\base_events.py", line 571, in run_until_complete

    self.run_forever()
  File "C:\Python37\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Python37\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "tune.py", line 220, in on_done
    opt.tell(x, -y)  # opt is minimizing
  File "C:\Python37\lib\site-packages\skopt\optimizer\optimizer.py", line 443, i
n tell
    return self._tell(x, y, fit=fit)
  File "C:\Python37\lib\site-packages\skopt\optimizer\optimizer.py", line 486, i
n _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "C:\Python37\lib\site-packages\skopt\learning\gaussian_process\gpr.py", l
ine 195, in fit
    super(GaussianProcessRegressor, self).fit(X, y)
  File "C:\Python37\lib\site-packages\sklearn\gaussian_process\gpr.py", line 221
, in fit
    self.kernel_.bounds))]
  File "C:\Python37\lib\site-packages\sklearn\gaussian_process\gpr.py", line 465
, in _constrained_optimization
    fmin_l_bfgs_b(obj_func, initial_theta, bounds=bounds)
  File "C:\Python37\lib\site-packages\scipy\optimize\lbfgsb.py", line 199, in fm
in_l_bfgs_b
    **opts)
  File "C:\Python37\lib\site-packages\scipy\optimize\lbfgsb.py", line 335, in _m
inimize_lbfgsb
    f, g = func_and_grad(x)
  File "C:\Python37\lib\site-packages\scipy\optimize\lbfgsb.py", line 285, in fu
nc_and_grad
    f = fun(x, *args)
  File "C:\Python37\lib\site-packages\scipy\optimize\optimize.py", line 326, in
function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Python37\lib\site-packages\scipy\optimize\optimize.py", line 64, in _
_call__
    fg = self.fun(x, *args)
  File "C:\Python37\lib\site-packages\sklearn\gaussian_process\gpr.py", line 213
, in obj_func
    theta, eval_gradient=True)
  File "C:\Python37\lib\site-packages\sklearn\gaussian_process\gpr.py", line 427
, in log_marginal_likelihood
    K[np.diag_indices_from(K)] += self.alpha
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python37\lib\asyncio\base_subprocess.py", line 247, in _call_connecti
on_lost
    self._protocol.connection_lost(exc)
  File "C:\Python37\lib\site-packages\chess\engine.py", line 679, in connection_
lost
    self.command._engine_terminated(self, code)
  File "C:\Python37\lib\site-packages\chess\engine.py", line 917, in _engine_ter
minated
    self.finished.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by fsmosca** [comment]
Tried another run, send ctrl+c after around 100 games, and I got this.
```
ERROR:asyncio:unhandled exception during asyncio.run() shutdown
task: <Task finished coro=<main() done, defined at tune.py:240> exception=ValueE
rror('math domain error')>
Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Python37\lib\asyncio\base_events.py", line 571, in run_until_complete

    self.run_forever()
  File "C:\Python37\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Python37\lib\asyncio\base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Python37\lib\asyncio\windows_events.py", line 412, in select
    self._poll(timeout)
  File "C:\Python37\lib\asyncio\windows_events.py", line 715, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tune.py", line 352, in main
    pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
  File "tune.py", line 350, in score_to_elo
    return - 400 * math.log10(2 / (score + 1) - 1)
ValueError: math domain error
```

The log in -log-file does not capture it, only like that.
```
{"ahash": "c2386c289341304e2bb00eabeabe1074cf63e8c7fb83a61cd40bc569b345d1aa", "x": [124.0, 303.0, 530.0, 1019.0, 81.0, 86.0, 90.0, 118.0, 95.0], "y": 0.0}
{"ahash": "c2386c289341304e2bb00eabeabe1074cf63e8c7fb83a61cd40bc569b345d1aa", "x": [108.0, 329.0, 538.0, 998.0, 116.0, 99.0, 92.0, 126.0, 120.0], "y": 2.0}
{"ahash": "c2386c289341304e2bb00eabeabe1074cf63e8c7fb83a61cd40bc569b345d1aa", "x": [114.0, 331.0, 529.0, 1011.0, 116.0, 99.0, 125.0, 114.0, 116.0], "y": 0.0}
```

**Comment by thomasahle** [comment]
Currently n^2 samples are generated to explore the final model. If you set -n really large, the memory consumption makes sense. This number should probably be limited.

**Comment by thomasahle** [comment]
I've pushed an update that changes this to just n.
