### ISSUE TITLE
tune.py: exception raised with RF as base estimator

### ISSUE THREAD

**Issue by joergoster** [thomasahle/fastchess#20]
When summarizing best values of a tuning run with RF as base estimator, following error occured:

> Summarizing best values
> /usr/lib/python3.7/asyncio/unix_events.py:861: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
>   RuntimeWarning)
> Traceback (most recent call last):
>   File "tune.py", line 483, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "tune.py", line 463, in main
>     summarize(opt, samples=args.n)
>   File "tune.py", line 334, in summarize
>     pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
>   File "tune.py", line 332, in score_to_elo
>     return - 400 * math.log10(2 / (score + 1) - 1)
> ValueError: math domain error
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
>     from apport.fileutils import likely_packaged, get_recent_crashes
>   File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
>     from apport.report import Report
>   File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
>     import apport.fileutils
>   File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
>     from apport.packaging_impl import impl as packaging
>   File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
>     import apt
>   File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
>     import apt_pkg
> ModuleNotFoundError: No module named 'apt_pkg'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "tune.py", line 483, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "tune.py", line 463, in main
>     summarize(opt, samples=args.n)
>   File "tune.py", line 334, in summarize
>     pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
>   File "tune.py", line 332, in score_to_elo
>     return - 400 * math.log10(2 / (score + 1) - 1)
> ValueError: math domain error

**Comment by joergoster** [comment]
@thomasahle I'm sorry to say, but I still get an error with RF as base estimator.
Trying to get the best values from a log file, and right before the first call to score_to_elo() with y_pred[i] / 2 as argument in tune.py, I tried to print exactly that with
`        print(y_pred[i] / 2)
`

> Using [19.0, 39.0, 62.0, 17.0] => -2.0 from log-file
> Using [43.0, 6.0, 44.0, 79.0] => 0.0 from log-file
> Using [48.0, 6.0, 43.0, 78.0] => 1.0 from log-file
> Using [12.0, 11.0, 50.0, 25.0] => 0.0 from log-file
> Fitting first model
> Summarizing best values
> 0.7285084498834498    <== output of print(y_pred[i] / 2)
> /usr/lib/python3.7/asyncio/unix_events.py:861: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
>   RuntimeWarning)
> Traceback (most recent call last):
>   File "tune.py", line 490, in <module>
>     asyncio.run(main())
>   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
>     return future.result()
>   File "tune.py", line 470, in main
>     summarize(opt, samples=args.n)
>   File "tune.py", line 340, in summarize
>     pm = max(abs(score_to_elo(y_pred[i] / 2 + sigma[i] / 2) - elo),
>   File "tune.py", line 336, in score_to_elo
>     return -400 * math.log10(2 / (score + 1) - 1)
> ValueError: math domain error

From my understanding `y_pred[i] / 2` can be 1, -1, -0.5, 0.0, 4.5, etc., but not 0.7285084498834498 ...
Am I wrong?

**Comment by joergoster** [comment]
OK, I had to comment out all of the elo stuff, then it works!

> Fitting first model
> Summarizing best values
> Best expectation (κ=0): [49.  5. 42. 78.]
> Best expectation (κ=1): [49.  5. 42. 78.]
> Best expectation (κ=2): [49.  5. 42. 78.]
> Best expectation (κ=3): [49.  5. 42. 78.]

**Comment by joergoster** [comment]
@thomasahle I wonder why there is no method in the Optimizer class which simply returns the best values of the current state.

From what I understand the optimizer keeps track of them in an OptimizeResult object.

> Returns
> 
>     res [OptimizeResult, scipy object]: The optimization result returned as a OptimizeResult object. Important attributes are:
>         x [list]: location of the minimum.
>         fun [float]: function value at the minimum.
>         models: surrogate models used for each iteration.
>         x_iters [list of lists]: location of function evaluation for each iteration.
>         func_vals [array]: function value for each iteration.
>         space [Space]: the optimization space.
>         specs [dict]`: the call specifications.
>         rng [RandomState instance]: State of the random state at the end of minimization.
> 

Can we use `expected_minimum(res, n_random_starts=20, random_state=None)` for this?
